language: php
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "vendor"

php:
  - 7.1
  - 5.6

dist: trusty

branches:
  only:
    - 8.x-1.x

mysql:
  database: drupal
  username: root
  encoding: utf8

scripts:
  - scripts/travis/quick-install-test.php
